version: '3.8'

services:
  sla_tracker:
    build:
      context: ./src/services/SLA_tracker/
      dockerfile: Dockerfile
      additional_contexts:
        common: ./src/common/
    container_name: sla_tracker_app
    restart: always
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./config:/app/config

  ticket_tracker:
    build:
      context: ./src/services/ticket_tracker/
      dockerfile: Dockerfile
      additional_contexts:
        common: ./src/common/
    container_name: ticket_tracker_app
    restart: always
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis

  commands_handler:
    build:
      context: ./src/services/commands_handler/
      dockerfile: Dockerfile
      additional_contexts:
        common: ./src/common/
    container_name: commands_handler_app
    restart: always
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  