services:
  sla_tracker:
    build:
      context: .
      dockerfile: src/services/SLA_tracker/Dockerfile
    container_name: sla_tracker_app
    restart: on-failure
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./config:/app/config
    networks:
      - bot_network
      - monitoring

  ticket_tracker:
    build:
      context: .
      dockerfile: src/services/ticket_tracker/Dockerfile
    container_name: ticket_tracker_app
    restart: on-failure
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis
    networks:
      - bot_network
      - monitoring

  commands_handler:
    build:
      context: .
      dockerfile: src/services/commands_handler/Dockerfile
    container_name: commands_handler_app
    restart: on-failure
    environment:
      - PYTHONPATH=/app   
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./ansible/:/app/ansible/
      - ./config:/app/config
      - ./scripts:/app/scripts
    networks:
      - bot_network
      - monitoring

  redis:
    image: "redis:alpine"
    container_name: redis_db
    restart: on-failure
    volumes:
      - redis_data:/data
    networks:
      - bot_network
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/etc/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
  
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    restart: on-failure
    environment:
      - REDIS_ADDR=redis://redis:6379
    command:
      - '--check-keys=1=tickets:known,0=tickets:new'
    ports:
      - "9121:9121"
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=asdqwe123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
  
networks:
  bot_network:
    driver: bridge
  
  monitoring:
    driver: bridge